production:
  sessions:
    default:
      database: omnisentry
      hosts:
        - localhost:27017

development:
  sessions:
    default:
      database: omnisentry_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: omnisentry_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
